eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.191.1:8081/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
server:
  port: 8080
spring:
  application:
    name: service-ribbon
  cloud:
      client.ipAddress: 192.168.191.1
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-hi
